spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect



  mail:
    host: localhost
    port: 9025

    server:
      port: 9191
